language: csharp

sudo: false # use the new container-based Travis infrastructure

before_install:
  - chmod +x build.sh

matrix:
  include:
    dotnet: 3.1.301

script:
  - ./build.sh All

branches:
  except:
    - gh-pages
